- name: Disable MySQL module
  ansible.builtin.command: dnf module disable mysql -y

- name: Copy mysql repo 
  ansible.builtin.copy:
    src: mysql.repo 
    dest: /etc/yum.repos.d/mysql.repo

- name: Install MySQL Server
  ansible.builtin.dnf:
    name: mysql-community-server
    state: present 

- name: Enable and Start mysql
  ansible.builtin.service:
    name: mysqld 
    enabled: yes 
    state: started

- name: Set Root Password 
  ansible.builtin.command: mysql_secure_installation --set-root-pass RoboShop@1