- name: App Setup
  ansible.builtin.import_role:
    name: common # Define the role
    tasks_from: app-setup # define the task you want to call
    
- name: Golang Setup
  ansible.builtin.import_role:
    name: common # Define the role
    tasks_from: golang-setup # define the task you want to call

- name: Systemd Setup and Restart {{component}}
  ansible.builtin.import_role:
    name: common # Define the role
    tasks_from: systemd-setup # define the task you want to call