- name: Stop {{component}}
  tags:
    - deployment
  tasks:
    - name: Stop the {{component}}
      ansible.builtin.servcie:
        name: "{{component}}"
        state: stopped

- name: recursively remove app directory
  tags:
    - deployment
  ansible.builtin.file:
    path: /app
    state: absent 

- name: create /app directory
  tags:
    - deployment
  ansible.builtin.file:
    path: /app 
    state: directory

- name: download {{component}}.zip
  tags:
    - deployment
  ansible.builtin.get_url:
        url: https://roboshop-builds.s3.amazonaws.com/{{component}}.zip
        dest: /tmp

- name: extract {{component}}.zip
  tags:
    - deployment
  ansible.builtin.unarchive:
        src: /tmp/{{component}}.zip
        dest: /app
        remote_src: yes 

- name: install dependencies
  tags:
    - deployment
  ansible.builtin.command: npm install 
  args:
    chdir: /app 

- name: Daemon reload
  tags:
    - deployment
  ansible.builtin.systemd_service:
    daemon_reload: true

- name: start the {{component}}
  tags:
    - deployment
  ansible.builtin.service:
    name: "{{component}}"
    enabled: yes
    state: started

    