- name: Install mysql client 
  ansible.builtin.dnf: 
    name: mysql 
    state: present 

- name: check cities schema exist or not
  ansible.builtin.command: mysql -h {{MYSQL_HOST}} -uroot -p{{mysql_password}} -sN -e "SELECT COUNT(*) FROM INFORMATION_SCHEMA.SCHEMATA WHERE SCHEMA_NAME= 'cities'"
  register: cities_schema

- name: print the cities schema output
  ansible.builtin.debug:
    msg: "Cities count is {{cities_schema}}"

- name: Load cities data into mysql 
  ansible.builtin.shell: mysql -h {{MYSQL_HOST}} -uroot -p{{mysql_password}} < /app/schema/shipping.sql 
  when: cities_schema.stdout == "0"
