- name: disable the nodejs 10 and enable nodejs 18
  # ansible.builtin.command: dnf module disable nodejs -y ; dnf module enable nodejs:18 -y
  ansible.builtin.shell: dnf module disable nodejs -y ; dnf module enable nodejs:18 -y

- name: Install nodejs
  ansible.builtin.package:
    name: nodejs
    state: present

- name: install dependencies
  ansible.builtin.command: npm install 
  args:
    chdir: /app 